# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Musings
tagline:             and notes
url:                 
paginate:            1
baseurl:             "http://pmsppinto.github.io/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Paulo Kauscher Pinto

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/pmsppinto/pmsppinto.github.io
