# Permalinks
permalink:           pretty

# Setup
title:               Musings and notes
tagline:             ...
url:                 http://pmsppinto.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:             :compressed

# About/contact
author:
  name:              Paulo Kauscher Pinto
  url:               https://pmsppinto.github.io
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/pmsppinto/pmsppinto.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
